---
- hosts: de9to
  become: true
  vars:
  - componyName: "mithunTehno"
  - location: "mumbai"
  tasks:
  - name: update
    apt:
      # upgrede: dist
      update_cache: yes
  - name: Install Apache2
    apt:
      name: apache2
      state: present
  # - name: start service
  #   service:
  #     name: apache2
  #     state: started  # we need to stop nginx if its running
  #     enabled: true
  - name: copy index.html
    template:
      src: '/home/ansible/ansible/index.html'
      dest: '/var/www/html/index.html'


