---
- hosts: de9to
  become: true
  tasks:
  # - name: upgrede
  #   apt:
  #     upgrede: dist


  - name: Install Apache2
    apt:
      upgrede: dist
      update_cache: yes
      name: apache2
      state: present
      state: enabled

