---
- hosts: de9to
  become: true
  tasks:
  - name: upgrede
    apt:
      # upgrede: dist
      update_cache: yes
  - name: Install Apache2
    apt:
      name: apache2
      state: present
  - name: start service
    service:
      name: apache2
      state: started  # we need to stop nginx if its running
      enabled: true
  - name: copy index.html
    copy:
    content: '<h1>Hello, World!</h1>'
    dest: /var/www/html/index.html
    

