---
- hosts: de9to
  become: true
  vars:
  # - domain: "wordpress.easesmith.com"
  - componyName: "dento"
  - location: "Lucknow"
  tasks:
  - name: copy index.html
    template: # var apply when copy
      src: '/home/ansible/ansible/index.html'
      dest: '/var/www/html/index.html'
  - name: nginx conf
    copy: 
      src: "./node"
      dest: "/etc/nginx/sites-available/node"
    notify: reload nginx Server
  - name: create symlink nginx conf
    file: 
      src: "/etc/nginx/sites-available/node"
      dest: "/etc/nginx/sites-enabled/node"
      state: link
    notify: reload nginx Server
  
  handlers: # handler is special tasks, which execute notified by other tasks
  - name: reload nginx Server
    service: 
      name: nginx
      state: reloaded
      enabled: true

  

    