---
- hosts: de9to
  become: true
  #vars:
  #- domain: www.easmith.com
  tasks:
  - name: nginx conf
    copy: 
      src: "./node"
      dest: "/etc/nginx/sites-available/node"
    notify: reload nginx Server
  - name: create symlink nginx conf
    file: 
      src: "/etc/nginx/sites-available/node"
      dest: "/etc/nginx/sites-enabled/node"
      state: link
    notify: reload nginx Server
  
  handlers: # handler is special tasks, which execute notified by other tasks
  - name: reload nginx Server
    service: 
      name: nginx
      state: reloaded 
      enabled: true

  

    