---
- hosts: all
  become: true
  tasks:
  - name: Create a file
    ansible.builtin.file: 
      path: "/tmp/ansible-demo.sh"
      mode: 0777
      owner: ansible
      group: root
      state: touch
