---
- hosts: de9to
  become: true
  tasks:
  - name: Create a file
    file: 
      path: "/etc/nginx/sites-available/wordpress"
      mode: 0777
      owner: ansible
      group: root
      state: touch
