---
- hosts: de9to
  become: true
  tasks:
  - name: create a symlink
    file: 
      scr: /etc/nginx/sites-available/wordpress
      dest: /etc/nginx/sites-enabled/wordpress
      owner: ansible
      group: ansible
      state: link
