---
- hosts: de9to
  become: true
  tasks:
  - name: Change file ownership, group and permissions
    file:
      path: /etc/nginx/sites-available/wordpress
      owner: ansible
      group: ansible
      mode: '0644'
  - name: create a symlink
    file: 
      src: /etc/nginx/sites-available/wordpress
      dest: /etc/nginx/sites-enabled/wordpress
      owner: ansible
      group: ansible
      state: link
