# docker-compose up -d
# docker-compose down
version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "{{port}}:80"  # Expose WordPress on port 8080
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Z9@9arzatt7!
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress_data:/var/www/html  # Mount volume to persist WordPress data
    networks:
      - wordpress_network

  db:
    image: mysql:9.0.1
    container_name: wordpress_db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Z9@9arzatt7!
      MYSQL_ROOT_PASSWORD: Z9@9arzatt7!

    volumes:
      - ./db_data:/var/lib/mysql  # Mount volume to persist MySQL data
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_network:
