---
- hosts: abhicare
  become: true
  vars:
  - port: "8083"
  tasks:
  - name: create Dir "wordpress"
    file:
      state: directory
      path: "/home/shubham/wordpress"
      mode: "0755"
      owner: shubham
      group: shubham
  - name: Deploy docker-compose.yml file
    template:
      src: "./docker-compose.yml"
      dest: "/home/shubham/wordpress/docker-compose.yml"
      mode: "0755"
      owner: shubham
      group: shubham
  - name: install wp on docker  
    command: > 
      docker-compose up -d  
    args: 
        chdir: "/home/shubham/wordpress" 


     