---
- hosts: abhicare
  become: true
  vars:
  - port: "8083"
  tasks:
  - name: Install wordpress
    file:
      state: directory
      path: "/home/shubham/wordpress"
      mode: "0755"
      owner: shubham
      group: shubham
    template:
      src: "./docker-compose.yml"
      dest: "/home/shubham/wordpress/docker-compose.yml"
      group: shubham
      owner: shubham
      mode: "0755"




     